Make decrypt_secrets non blocking

diff --git a/tools/secrets/decrypt_secrets b/tools/secrets/decrypt_secrets
--- a/tools/secrets/decrypt_secrets
+++ b/tools/secrets/decrypt_secrets
@@ -12,3 +12,10 @@ fi
 
 mkdir -p "$CLEAR_DIR"
 encfs "${PWD}/$SECRET_DIR" "${PWD}/$CLEAR_DIR"
+
+
+if [ $? -ne 0 ]; then
+    RED='\033[0;31m'
+    NC='\033[0m'
+    echo -e "${RED}Failed to decrypt secret path, continuing anyway${NC}"
+fi
